### ISSUE TITLE
Possible buffering issue with output from print statements

### ISSUE THREAD

**Issue by davidjfinton** [pflagerd/code-editor-flask#33]
Output that contains print statements may not appear in chronological order.  Specifically, ordinary print statements may appear to have their output delayed in the console.  This may be a python quirk.  A workaround is to include the parameter flush = True in the print statement.

For example:

import os
print( 'happy to be here' )
os.system( 'pwd' )

may produce the following:

/home/david/repos/code-editor-flask
happy to be here

The 'correct' (to us) order is restored by writing the print statement as follows:

print( 'happy to be here', flush = True )

**Comment by pflagerd** [comment]
See #34. Solved. Closing.
